language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  matrix:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=WTForms==2.0

install:
  - "pip install $WTFORMS"
  - pip install -e ".[test]"
script:
  - python setup.py test
